DROP USER coupang CASCADE;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER coupang IDENTIFIED BY coupang;

GRANT RESOURCE, CONNECT TO coupang;

ALTER USER coupang DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

--------------------------------------------------
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER	NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME" VARCHAR2(30) NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(N:탈퇴X, Y: 탈퇴O)';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "CH_MEMBER_DEL_FL" 
CHECK("MEMBER_DEL_FL" IN ('N', 'Y'));


CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03'
	, '이옥순', DEFAULT, DEFAULT);

CREATE TABLE "CART" (
	"CART_NO" NUMBER NOT NULL,
	"CART_TITLE" VARCHAR2(300) NOT NULL,
	"CART_MEMO" VARCHAR2(500),
	"CART_DATE" DATE	DEFAULT SYSDATE NOT NULL,
	"CART_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO" NUMBER NOT NULL
);

COMMENT ON COLUMN "CART"."CART_NO" IS '카트 번호(SEQ_CART_NO)';

COMMENT ON COLUMN "CART"."CART_TITLE" IS '물건 이름';

COMMENT ON COLUMN "CART"."CART_MEMO" IS '물건 메모';

COMMENT ON COLUMN "CART"."CART_DATE" IS '물건 선택일';

COMMENT ON COLUMN "CART"."CART_DEL_FL" IS '삭제 여부(N : 삭제X , Y : 삭제O)';

COMMENT ON COLUMN "CART"."MEMBER_NO" IS '작성자 회원 번호';

CREATE SEQUENCE SEQ_CART_NO NOCACHE;

ALTER TABLE "CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY (
	"CART_NO"
);

ALTER TABLE "CART" ADD CONSTRAINT "FK_MEMBER_TO_CART" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

COMMIT;

